---
title: "AGU Map"
author: "Ryan Gan"
date: "12/1/2017"
output: html_document
---

```{r setup, echo=F, warning=F, message=F}
library(tidyverse) # general data wrangle

# knitr options
knitr::opts_chunk$set(fig.width=8, fig.height=6, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

## Document Purpose

Map for Kate and Jeff for AGU to demonstrate variability in health outcomes.

```{r data wrangle}
# saba timestratifed to counts for fills with a icd9 as well
saba <- read_csv("./data/health/2013-oregon_casecross_saba.csv") %>% 
  # get rid of referent values
  filter(outcome == 1)

# time sereis of saba
saba_ts <- saba %>% 
  group_by(MSA, date) %>% 
  summarise(saba_n = n()) %>% 
  mutate(metroarea = case_when(
    MSA == 13460 ~ "Bend-Redmond",
    MSA == 18700 ~ "Corvallis",
    MSA == 21660 ~ "Eugene-Springfield",
    MSA == 32780 ~ "Medford",
    MSA == 38900 ~ "Portland-Vancouver-Beaverton",
    MSA == 41420 ~ "Salem",
    MSA == 41999 ~ "Not in MSA"))
```

