---
title: "Oregon_Wildfire_reduced"
author: "Jingyang Liu"
date: "February 15, 2017"
output: html_document
---

## Explore Data Structure and Cleaning

The Oregon data contains 77069320 obsversations in total in year of 2013, which is a big data set. We want to figure out the structure for this data set and do some basic cleaning. 

```{r}
library(dplyr)
library(data.table)

# import data ------------------------------------------------------------------
# Read in first 2000000 lines for exploration.

# read_path <- paste0("./data/gan_episodes_of_care.txt")
# oregon_df <- fread(read_path, sep = "|", nrows = 200000, showProgress = T)
# fwrite(oregon_df, "./data/oregon_epis_care_reduced.csv")

# I wrote a reduced dataframe of 2000,000 rows to get an idea of data structure

# import the reduced dataframe
start_time <- Sys.time()

oregon_df <- fread("./data/oregon_epis_care_reduced.csv", sep = ",")

stop_time <-  Sys.time() - start_time 

# time it took
stop_time # 15.83603 secs

```

#  The variable "clmstatus" is ..... It is a binary

```{r claim status}

# Explore data structure, try like clmstatus
summary(oregon_df)
summary(as.factor(oregon_df$clmstatus))

```



## Clean data

```{r }
# Clean data, 76986701 left (maybe later)
#oregon_full_df <- oregon_full %>%
  # filter non-missing value of year of birth, gender, race, STATE
#  filter (is.na(yob)==F) %>%
#  filter (gender!='U') %>%
#  filter (is.na(race)==F) %>%
#  filter (STATE!='')

# Explore no dx1 and no ndc, see if the dx2 or other reasons, 1042984 obs
# oregon_full_miss <- oregon_full %>%
#  filter (dx1=='*NULL*') %>%
#  filter (ndc=="")

# fwrite(oregon_full_miss, "../data/oregon_full_miss.csv")

# read_path1 <- paste0("./data/oregon_full_miss.csv")
# oregon_miss <- fread(read_path1, sep = ",")

# oregon_miss_df <- oregon_miss %>%
#   filter (dx2!='*NULL*') # 981 obs


# filter dx1, no ndc, 52490460
# oregon_full_dx1 <- oregon_full_df %>%
#   filter (dx1!='*NULL*')


# filter ndc, no dx1, 23453379
# oregon_full_ndc <- oregon_full_df %>%
#  filter (ndc!="")

# fwrite(oregon_full_dx1, "../data/oregon_full_dx1.csv")
# fwrite(oregon_full_ndc, "../data/oregon_full_ndc.csv")




```







